apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: vllm-server
  podMetricsEndpoints:
  - port: metrics
    path: /
    interval: 15s
