apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flask-crud-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: flask-crud-api
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 15s
